# Generated by Django 4.2.7 on 2023-11-21 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('prezime', models.CharField(max_length=255)),
                ('datum_rodjenja', models.DateField()),
                ('pol', models.CharField(max_length=10)),
                ('kontakt_telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresa', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_id', models.CharField(editable=False, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_meeting_id', models.IntegerField(editable=False)),
                ('datum_sastanka', models.DateField(blank=True, null=True)),
                ('dijagnoza_za_ishranu', models.TextField(blank=True, null=True)),
                ('preporuka_za_ishranu', models.TextField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('telesna_masa', models.FloatField(blank=True, null=True)),
                ('visina', models.FloatField(blank=True, null=True)),
                ('procenat_spoljasnje_masti', models.FloatField(blank=True, null=True)),
                ('procenat_unutrasnje_masti', models.FloatField(blank=True, null=True)),
                ('procenat_misica', models.FloatField(blank=True, null=True)),
                ('procenat_vode', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patients')),
            ],
        ),
    ]
